[LM-10498] Added post detail screen
LikeMindsCommunity/likeminds-feed-reactnative pull request #7
Opened 2024-02-01 07:54 UTC by prabha-likeminds

1. Added post detail list

2024-02-05 10:02 UTC, jaixchaudhary commented on example/SampleApp/sampleApp/App.tsx
> +            <Stack.Screen name={'PostDetail'} component={PostDetail} />
import screen name strings from a constant file

2024-02-05 10:02 UTC, jaixchaudhary commented on example/SampleApp/sampleApp/index.js
> +const myClient = initMyClient('071f9d47-9905-44fc-a4ef-612cb75ce45a');
remove API key from here

2024-02-05 10:03 UTC, jaixchaudhary commented on example/SampleApp/sampleApp/ios/sampleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file

2024-02-05 10:04 UTC, jaixchaudhary commented on example/SampleApp/sampleApp/package.json
> +    "react-native-screens": "^3.29.0",
remove carets from dependencies

2024-02-05 10:23 UTC, jaixchaudhary commented on likeminds-feed-reactnative-integration/context/postListContext.tsx
> +  route: any;
add `navigation` and `route` types

2024-02-05 10:23 UTC, jaixchaudhary commented on likeminds-feed-reactnative-integration/context/postListContext.tsx
> +  navigation: any;
add `navigation` type

2024-02-05 10:40 UTC, jaixchaudhary commented on likeminds-feed-reactnative-integration/navigation/SwitchComponent.tsx
> +          <Stack.Screen name={'POST_LIST'} component={PostsList} />
import `POST_LIST` string as well

2024-02-05 10:53 UTC, jaixchaudhary commented on likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
>                : dispatch()
why there is empty dispatch method call?

2024-02-12 10:41 UTC, prabha-likeminds commented on likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
>                : dispatch()
that will be handled later with toast message, have to write that empty dispatch to avoid errors in condition

2024-02-14 05:52 UTC, ishaan1607 requested changes

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/context/postListContext.tsx
> +  route: any;
@prabha-likeminds these comments are still unresolved?

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/context/postListContext.tsx
> +  navigation: any;
@prabha-likeminds these comments are still unresolved?

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
> +      if (memberData?.state !== 1) {
use enums for this check. Like `STATE_ADMIN = 1`, `STATE_MEMBER = 4`

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
> +          (item: any) => item?.state === 9
create type/interface for the rights.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
> +          (item: any) => item?.state === 9
use enums for rights state, like `RIGHT_CREATE_POST = 9`

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
> +      dispatch(deletePostStateHandler(payload.postId) as any);
why "as any", is it still not solved?

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
> +interface postDetailStyleProps {
rename postDetailStyleProps to `PostDetailStyleProps`

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
> +const UniversalFeed = ({ navigation, route ,children}: any) => {
create a type/interface for props, don't use any

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/store/actions/login.ts
> +export const initiateUser = (payload: any, showLoader: boolean) => () => {
why it is `any`, it should be specific, request types.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/store/actions/feed.ts
> +export const getFeed = (payload: any, showLoader: boolean) => () => {
why it is `any`, it should be specific, request types.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/store/actions/feed.ts
All functions have `payload: any`, why it is `any`, it should be specific, request types/class, which we send to data layer.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/store/actions/login.ts
All functions have `payload: any`, why it is `any`, it should be specific, request types/class, which we send to data layer.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/store/actions/postDetail.ts
All functions have `payload: any`, why it is `any`, it should be specific, request types/class, which we send to data layer.

2024-02-14 05:52 UTC, ishaan1607 commented on likeminds-feed-reactnative-integration/utils/mentionToRouteConverter.ts
> +      return `<<${name}|route://${name}>>`;
is this route right?

2024-02-19 04:59 UTC, prabha-likeminds commented on likeminds-feed-reactnative-integration/utils/mentionToRouteConverter.ts
> +      return `<<${name}|route://${name}>>`;
yes

2024-02-19 07:46 UTC, jaixchaudhary commented on example/SampleApp/sampleApp/App.tsx
> +import * as Navi from './RootNavigation'
What is the use of `Navi`, why import it if not using it, if using it then name it correctly like `RootStackNavigation`

2024-02-19 07:50 UTC, jaixchaudhary commented on likeminds-feed-reactnative-integration/store/actions/postDetail.ts
> +export const replyCommentStateHandler = (payload?: ReplyCommentState) => () => {
why payload is optional

2024-02-19 07:59 UTC, prabha-likeminds commented on example/SampleApp/sampleApp/App.tsx
> +import * as Navi from './RootNavigation'
not in use, removed it

2024-02-19 08:16 UTC, merged